### ISSUE TITLE
Issue tracker for images simplifications

### ISSUE THREAD

**Issue by jngrad** [espressomd/docker#165]
* [x] Reduce duplications in Ubuntu-based Dockerfiles (@KaiSzuttor, #163)
* [x] Setup Clang-9 in Ubuntu 20.04 dockerfile (@RudolfWeeber, espressomd/espresso#3627)
   * sort out Clang-tidy issues (espressomd/espresso#3526)
   * install Clang-9 on ICP machines
   * only then, open a PR on espressomd/espresso to replace `clang:6.0` by `ubuntu:20.04` and apply clang-format-9
* [x] Setup CUDA in Ubuntu 20.04 dockerfile (@RudolfWeeber, espressomd/espresso#3611)
* [x] Use same packages across all linux flavors and cleanup dockerfiles (@jngrad, #169, #172)
* [x] push the Travis image to DockerHub (#167) and explain it in the CI docs (@jngrad)
